apiVersion: v1
kind: Service
metadata:
  name: service-sirh
spec:
  selector:
    app: sirh-backend
    type: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099
      name: http-backend
      nodePort: 32106
    
