apiVersion: v1
kind: Service
metadata:
  name: service-gira
spec:
  selector:
    app: gira-backend
    type: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      name: http-backend
    
