apiVersion: v1
kind: Service
metadata:
  name: service-rp
spec:
  selector:
    app: rp-backend
    type: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: http-backend
      nodePort: 32225
    
