apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-front
  labels:
    app: admin-front
    type: front
spec:
  selector:
    matchLabels:
      app: admin-front
      type: front
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin-front    
        type: front
    spec:
      nodeSelector:
        kubernetes.io/hostname: workernode2
      imagePullSecrets:
       - name: regcred      
      containers:
        - name: admin-front
          image: 192.168.2.19:5000/frontadmine:21
          resources:
            requests:
              memory: "700Mi"
              cpu: "400m"
            limits:
              memory: "3Gi"
              cpu: "5"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
         
          
          
          
      