apiVersion: v1
kind: Service
metadata:
  name: service-ged
spec:
  selector:
    app: ged-backend
    type: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 7071
      targetPort: 7071
      name: http-backend
      nodePort: 31311
    
