apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  POSTGRES_DB: a2V5Y2xvYWs=
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: a2V5Y2xvYWs=
  KEYCLOAK_ADMIN: YWRtaW45
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW45
