apiVersion: v1
kind: Service
metadata:
  name: service-admin-dev
spec:
  selector:
    app: admin-backend-dev
    type: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 11994
      targetPort: 11994
      name: http-backend
      nodePort: 32004
      
      
      
      
      
      
      
      
   
